In [37]:
import csv
import pandas as pd

class HashTable:
    def __init__(self, capacity: int):
        self.capacity = capacity
        self.buckets = [[] for _ in range(capacity)]

    def get_hash(self, key):
        if key % self.capacity != key:
            raise KeyError("Элемент не найден")
        else:
            return key

    def add(self, key, value):
        index = self.get_hash(key)
        for k, v in self.buckets[index]:
            if k == key:
                v.append(value)
                return
        self.buckets[index].append((key, [value]))

    def find(self, key):
        index = self.get_hash(key)
        for k, v in self.buckets[index]:
            if k == key:
                return v
        return None

    def remove(self, key):
        index = self.get_hash(key)
        bucket = self.buckets[index]
        for i, (k, v) in enumerate(bucket):
            if k == key:
                del bucket[i]
                return
        raise KeyError("Элемент не найден")

    def search(self, key):
        index = self.get_hash(key)
        for k, v in self.buckets[index]:
            if k == key:
                return True
        return False

def selection_sort(arr, key):
    n = len(arr)
    for i in range(n):
        min_index = i
        for j in range(i + 1, n):
            if arr[j][key] < arr[min_index][key]:
                min_index = j
        arr[i], arr[min_index] = arr[min_index], arr[i]
    return arr

def read_data(file_name='orders.csv'):
    data = []
    try:
        with open(file_name, 'r', newline='', encoding='utf-8') as csvfile:
            csvreader = csv.reader(csvfile)
            next(csvreader)
            for row in csvreader:
                data.append(row)
        return data
    except Exception as e:
        print(f"Ошибка чтения файла - {file_name}: {str(e)}")
        return []

def show_csv_table(file='orders.csv'):
    try:
        df = pd.read_csv(file)
        df.index = [''] * len(df['Номер заказа'])
        display(df)
    except Exception as e:
        print(f"Проблемы с чтением файла - {file}: {str(e)}")

def show_table(data, length=1):
    df = pd.DataFrame(data)
    df.index = [''] * length
    display(df)

def pd_read_data(file='orders.csv'):
    try:
        df = pd.read_csv(file)
        return df
    except Exception as e:
        print(f"Проблема с чтением файла - {file} с помощью pandas: {str(e)}")

file_name = 'orders.csv'
sales_data = read_data(file_name) # Чтение данных из CSV файла
sales_data_dict = [dict(zip(['order_columns', 'order_date', 'name', 'category', 'count', 'price', 'price_all'], row)) for row in sales_data]
sorted_sales_data = selection_sort(sales_data_dict, 'order_date') # Сортировка данных по дате заказа
show_table(sorted_sales_data, len(sorted_sales_data))

,order_columns,order_date,name,category,count,price,price_all
,1,2024-05-15,Ноутбук игровой Thunderobot 911S,Ноутбуки,7,77999,545993
,5,2024-05-15,Телевизор Philips 55PUS8057/60,Телевизоры,10,44999,449990
,4,2024-05-16,Ноутбук HUAWEI MateBook D 16,Ноутбуки,19,49999,949981
,2,2024-05-16,Смартфон Apple iPhone 13 128GB,Смартфоны,23,65999,1517977
,3,2024-05-16,Смартфон HONOR 90 8/256GB,Смартфоны,23,39999,919977
,6,2024-05-16,Телевизор Philips 50PUS8507/60,Телевизоры,15,46999,704985
,7,2024-05-16,Умная колонка Яндекс Станция Миди с Алисой,Портативная акустика,8,16999,135992
,8,2024-05-16,Смартфон OPPO A78 8/256GB,Смартфоны,7,16999,188993
,9,2024-05-16,Стиральная машина узкая Haier HW60-BP12919A,Стиральные машины,13,32999,428987
,10,2024-05-16,Телевизор Toshiba 50C350LE,Телевизоры,3,39999,119997
,11,2024-05-16,Телевизор Haier 50 Smart TV S3,Телевизоры,6,44999,269994
,12,2024-05-16,Ноутбук Apple MacBook Air 13 M1,Ноутбуки,21,90999,1910979
,13,2024-05-16,Смартфон Apple iPhone 14 Pro Max 1ТБ,Смартфоны,6,209190,1255140
,14,2024-05-16,Холодильник Haier C2F636CXMV,Холодильники,4,55999,223996
,15,2024-05-16,Смартфон Samsung Galaxy S23 FE 128GB,Смартфоны,14,59999,839986
,16,2024-05-16,Стиральная машина узкая Beko WSPE7612W,Стиральные машины,20,24999,499980

,order_columns,order_date,name,category,count,price,price_all
,1,2024-05-15,Ноутбук игровой Thunderobot 911S,Ноутбуки,7,77999,545993
,5,2024-05-15,Телевизор Philips 55PUS8057/60,Телевизоры,10,44999,449990
,4,2024-05-16,Ноутбук HUAWEI MateBook D 16,Ноутбуки,19,49999,949981
,2,2024-05-16,Смартфон Apple iPhone 13 128GB,Смартфоны,23,65999,1517977
,3,2024-05-16,Смартфон HONOR 90 8/256GB,Смартфоны,23,39999,919977
,6,2024-05-16,Телевизор Philips 50PUS8507/60,Телевизоры,15,46999,704985
,7,2024-05-16,Умная колонка Яндекс Станция Миди с Алисой,Портативная акустика,8,16999,135992
,8,2024-05-16,Смартфон OPPO A78 8/256GB,Смартфоны,7,16999,188993
,9,2024-05-16,Стиральная машина узкая Haier HW60-BP12919A,Стиральные машины,13,32999,428987
,10,2024-05-16,Телевизор Toshiba 50C350LE,Телевизоры,3,39999,119997
,11,2024-05-16,Телевизор Haier 50 Smart TV S3,Телевизоры,6,44999,269994
,12,2024-05-16,Ноутбук Apple MacBook Air 13 M1,Ноутбуки,21,90999,1910979
,13,2024-05-16,Смартфон Apple iPhone 14 Pro Max 1ТБ,Смартфоны,6,209190,1255140
,14,2024-05-16,Холодильник Haier C2F636CXMV,Холодильники,4,55999,223996
,15,2024-05-16,Смартфон Samsung Galaxy S23 FE 128GB,Смартфоны,14,59999,839986
,16,2024-05-16,Стиральная машина узкая Beko WSPE7612W,Стиральные машины,20,24999,499980